"""Added new table Tags Posts Posts_tags_association_table

Revision ID: 9a7bb93cdc71
Revises: 2099cb57217e
Create Date: 2023-01-10 05:51:00.073991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a7bb93cdc71'
down_revision = '2099cb57217e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_app__posts_tags_association_table',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['blog_app__posts.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['blog_app__tags.id'], ),
    sa.PrimaryKeyConstraint('post_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog_app__posts_tags_association_table')
    # ### end Alembic commands ###
