"""Added access_token column to User model

Revision ID: 6b52979832e8
Revises: 9a7bb93cdc71
Create Date: 2023-01-22 12:51:06.570634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b52979832e8'
down_revision = '9a7bb93cdc71'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_app__users', sa.Column('access_token', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_blog_app__users_access_token'), 'blog_app__users', ['access_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blog_app__users_access_token'), table_name='blog_app__users')
    op.drop_column('blog_app__users', 'access_token')
    # ### end Alembic commands ###
