"""add column is_new on product table

Revision ID: 120618d4695d
Revises: f0367a240903
Create Date: 2023-02-02 13:45:58.514144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '120618d4695d'
down_revision = 'f0367a240903'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_new', sa.Boolean(), server_default='False', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('is_new')

    # ### end Alembic commands ###
