# Generated by Django 4.1.6 on 2023-02-20 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_animal_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalDetail',
            fields=[
                ('animal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='animals.animal')),
                ('biography', models.TextField()),
            ],
        ),
    ]
