# Generated by Django 4.1.6 on 2023-02-20 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_animaldetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('animal', models.ManyToManyField(to='animals.animal')),
            ],
        ),
    ]
